// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Cn = require("re-classnames/src/Cn.bs.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function FilterLink(Props) {
  var children = Props.children;
  var filter = Props.filter;
  var state = Props.state;
  var dispatch = Props.dispatch;
  var visibilityFilter = state[/* visibilityFilter */1];
  return React.createElement("a", {
              className: Cn.ifTrue("selected", filter === visibilityFilter),
              style: {
                cursor: "pointer"
              },
              onClick: (function (param) {
                  return Curry._1(dispatch, /* SetVisibilityFilter */Block.__(4, [filter]));
                })
            }, children);
}

var make = FilterLink;

exports.make = make;
/* react Not a pure module */
