// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var TodoItem$ReactHooksTemplate = require("./TodoItem.bs.js");
var Component2$ReactHooksTemplate = require("./Component2.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(TodoItem$ReactHooksTemplate.make, {
          id: 1,
          text: "fa",
          completed: false
        }), "index1");

ReactDOMRe.renderToElementWithId(React.createElement(Component2$ReactHooksTemplate.make, {
          greeting: "Hello!"
        }), "index2");

/*  Not a pure module */
