// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var App$ReactHooksTemplate = require("./App.bs.js");
var TodoStore$ReactHooksTemplate = require("./TodoStore.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(TodoStore$ReactHooksTemplate.AppStore[/* Provider */0][/* make */0], {
          children: React.createElement(App$ReactHooksTemplate.make, { }),
          store: TodoStore$ReactHooksTemplate.appStore
        }), "index");

/*  Not a pure module */
