// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Footer$ReactHooksTemplate = require("./Footer.bs.js");
var TodoList$ReactHooksTemplate = require("./TodoList.bs.js");
var TodoStore$ReactHooksTemplate = require("./TodoStore.bs.js");

function MainSection(Props) {
  var state = Props.state;
  var dispatch = Props.dispatch;
  var todosCount = TodoStore$ReactHooksTemplate.getTodosCount(state);
  var completedCount = TodoStore$ReactHooksTemplate.getCompletedCount(state);
  return React.createElement("section", {
              className: "main"
            }, todosCount > 0 ? React.createElement("span", undefined, React.createElement("input", {
                        defaultChecked: completedCount === todosCount,
                        className: "toggle-all",
                        type: "checkbox"
                      }), React.createElement("label", {
                        htmlFor: "toggle-all",
                        onClick: (function (param) {
                            return Curry._1(dispatch, /* ToggleAllTodos */0);
                          })
                      })) : null, React.createElement(TodoList$ReactHooksTemplate.make, {
                  state: state,
                  dispatch: dispatch
                }), todosCount > 0 ? React.createElement(Footer$ReactHooksTemplate.make, {
                    state: state,
                    dispatch: dispatch
                  }) : null);
}

var make = MainSection;

exports.make = make;
/* react Not a pure module */
