// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function TodoItem(Props) {
  Props.id;
  Props.text;
  Props.completed;
  return React.createElement("li", undefined);
}

var make = TodoItem;

exports.make = make;
/* react Not a pure module */
