// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var TodoItem$ReactHooksTemplate = require("./TodoItem.bs.js");
var TodoStore$ReactHooksTemplate = require("./TodoStore.bs.js");

function TodoList(Props) {
  var state = Props.state;
  var dispatch = Props.dispatch;
  return React.createElement("ul", {
              className: "todo-list"
            }, Belt_Array.map(TodoStore$ReactHooksTemplate.getFilteredTodos(state[/* visibilityFilter */1], state), (function (todo) {
                    return React.createElement(TodoItem$ReactHooksTemplate.make, {
                                id: todo[/* id */2],
                                text: todo[/* text */0],
                                completed: todo[/* completed */1],
                                dispatch: dispatch
                              });
                  })));
}

var make = TodoList;

exports.make = make;
/* react Not a pure module */
