// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function TodoItem(Props) {
  Props.id;
  Props.text;
  Props.completed;
  React.useState((function () {
          return false;
        }));
  localStorage.setItem("token", "tk");
  var token = localStorage.getItem("token");
  if (token !== null) {
    return React.createElement("li", undefined, token);
  } else {
    return React.createElement("li", undefined);
  }
}

var make = TodoItem;

exports.make = make;
/* react Not a pure module */
