// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Cn = require("re-classnames/src/Cn.bs.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var $$String = require("bs-platform/lib/js/string.js");

function TodoTextInput(Props) {
  var onSave = Props.onSave;
  var match = Props.text;
  var text = match !== undefined ? match : "";
  var placeholder = Props.placeholder;
  var editing = Props.editing;
  var newTodo = Props.newTodo;
  var match$1 = React.useState((function () {
          return text;
        }));
  var setText = match$1[1];
  var handleBlur = function (e) {
    if (newTodo) {
      return 0;
    } else {
      return Curry._1(onSave, e.target.value);
    }
  };
  var handleChange = function (e) {
    return Curry._1(setText, e.target.value);
  };
  var handleSubmit = function (e) {
    var text = $$String.trim(e.target.value);
    if (e.which === 13) {
      Curry._1(onSave, text);
      if (newTodo) {
        return Curry._1(setText, (function (param) {
                      return "";
                    }));
      } else {
        return 0;
      }
    } else {
      return 0;
    }
  };
  return React.createElement("input", {
              className: Cn.make(/* :: */[
                    Cn.ifTrue("edit", editing),
                    /* :: */[
                      Cn.ifTrue("new-todo", newTodo),
                      /* [] */0
                    ]
                  ]),
              autoFocus: true,
              placeholder: placeholder,
              type: "text",
              value: match$1[0],
              onKeyDown: handleSubmit,
              onBlur: handleBlur,
              onChange: handleChange
            });
}

var make = TodoTextInput;

exports.make = make;
/* react Not a pure module */
